"""CPG (Central Pattern Generator) experts for mujoco_playground locomotion.

A CPG is an open-loop sinusoidal pattern generator:
    action_i(t) = amp_i * sin(2π * freq * t + phase_i)

It plugs into the same `FunctionalExpertPolicy` interface as PID experts in
`target_gym.experts.pid`, so Ajax's gain-policy mode (SAC actor outputs
per-parameter log-multipliers on anchor gains) works out of the box.

Learnable fields (in order): ``frequency, amp_0, amp_1, ..., amp_{n-1}``.
Phases are **not** learnable: they are the gait coordination the expert
contributes, and additive modulation on cyclic quantities does not compose
cleanly with Ajax's multiplicative ``anchor * exp(ln10 * a)`` gain pipeline.

Tuned anchor parameters are loaded from ``AjaxExperiments/cpg_tuned_<env>.json``
(generated by ``AjaxExperiments/tune_cpg.py``).
"""

import json
import pathlib

import jax
import jax.numpy as jnp
from flax import struct

from target_gym.experts.pid import (
    FunctionalExpertPolicy,
    _LEARNABLE_GAINS_BY_STEP_FN,
    register_learnable_gains,
)

# ---------------------------------------------------------------------------
# Tuned-params store
# ---------------------------------------------------------------------------

_AJAX_EXP_ROOT = pathlib.Path(__file__).resolve().parents[4] / "AjaxExperiments"


def _load_tuned(env_name: str) -> dict | None:
    path = _AJAX_EXP_ROOT / f"cpg_tuned_{env_name.lower()}.json"
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return None


# ---------------------------------------------------------------------------
# CheetahRun CPG (6 actuators)
# ---------------------------------------------------------------------------

_N_CHEETAH = 6


@struct.dataclass
class CheetahCPGParams:
    """Static params for the CheetahRun CPG (6 actuators).

    Phases are fixed (non-learnable); frequency + amplitudes modulate via
    Ajax's gain-policy pipeline when `expert.learnable_fields` is read.
    """

    frequency: float
    amp_0: float
    amp_1: float
    amp_2: float
    amp_3: float
    amp_4: float
    amp_5: float
    phase_0: float
    phase_1: float
    phase_2: float
    phase_3: float
    phase_4: float
    phase_5: float
    dt: float  # env physics dt (CheetahRun = 0.01 s); not learnable


@struct.dataclass
class CPGState:
    time: float


def cpg_reset(params: CheetahCPGParams) -> CPGState:  # noqa: ARG001
    return CPGState(time=jnp.float32(0.0))


def cheetah_cpg_step(
    params: CheetahCPGParams, state: CPGState, obs: jnp.ndarray
) -> tuple[jnp.ndarray, CPGState]:
    """Open-loop sinusoidal CPG. ``obs`` is unused (pure pattern generator).

    Phase relationships encode the gait (contributed by the expert); the RL
    policy modulates frequency + amplitudes through the gain-policy interface.
    """
    t = state.time
    omega = 2.0 * jnp.pi * params.frequency
    amps = jnp.stack([params.amp_0, params.amp_1, params.amp_2,
                      params.amp_3, params.amp_4, params.amp_5])
    phases = jnp.stack([params.phase_0, params.phase_1, params.phase_2,
                        params.phase_3, params.phase_4, params.phase_5])
    action = amps * jnp.sin(omega * t + phases)
    # Clip to match env action range [-1, 1].
    action = jnp.clip(action, -1.0, 1.0)
    new_state = CPGState(time=t + params.dt)
    return action, new_state


# Register gain-policy learnable fields: frequency + 6 amplitudes.
# Phases stay at anchor values (gait coordination is the expert's contribution).
_CHEETAH_CPG_LEARNABLE = (
    "frequency", "amp_0", "amp_1", "amp_2", "amp_3", "amp_4", "amp_5",
)
register_learnable_gains(cheetah_cpg_step, _CHEETAH_CPG_LEARNABLE)


def make_cheetah_cpg(
    dt: float = 0.01,
) -> tuple[CheetahCPGParams, CPGState]:
    """CPG for CheetahRun. Loads tuned params from cpg_tuned_cheetahrun.json."""
    tuned = _load_tuned("cheetahrun")
    if tuned is not None:
        freq = float(tuned["frequency"])
        amps = [float(a) for a in tuned["amplitudes"]]
        phases = [float(p) for p in tuned["phases"]]
    else:
        # Hand-tuned fallback (gallop-ish gait, see eval_cpg_expert.py).
        freq = 2.5
        amps = [0.8, 0.8, 0.6, 0.8, 0.8, 0.6]
        phases = [0.0, 1.0, 2.0, jnp.pi / 2,
                  jnp.pi / 2 + 1.0, jnp.pi / 2 + 2.0]
    assert len(amps) == _N_CHEETAH and len(phases) == _N_CHEETAH
    params = CheetahCPGParams(
        frequency=freq,
        amp_0=amps[0], amp_1=amps[1], amp_2=amps[2],
        amp_3=amps[3], amp_4=amps[4], amp_5=amps[5],
        phase_0=phases[0], phase_1=phases[1], phase_2=phases[2],
        phase_3=phases[3], phase_4=phases[4], phase_5=phases[5],
        dt=float(dt),
    )
    return params, cpg_reset(params)


def make_cheetah_cpg_expert() -> FunctionalExpertPolicy:
    """Return a FunctionalExpertPolicy-wrapped Cheetah CPG.

    Plugs into Ajax's ``expert_policy=``/``eval_expert_policy=`` slots and
    supports the gain-policy mode via ``step_with_gains``.
    """
    params, zero_state = make_cheetah_cpg()
    return FunctionalExpertPolicy(params, zero_state, cheetah_cpg_step)


# ---------------------------------------------------------------------------
# BarkourJoystick CPG (12 actuators, classic trot gait)
# ---------------------------------------------------------------------------
#
# Actuator layout (from mujoco_playground.BarkourJoystick):
#   0 abduction_front_left   3 abduction_hind_left    6 abduction_front_right   9 abduction_hind_right
#   1 hip_front_left         4 hip_hind_left          7 hip_front_right        10 hip_hind_right
#   2 knee_front_left        5 knee_hind_left         8 knee_front_right       11 knee_hind_right
#
# Trot pairs diagonal legs: (front-left, hind-right) in phase,
# (front-right, hind-left) antiphase. Abduction is held near zero for forward
# trot; hips swing forward/back; knees lift during swing phase.


_N_BARKOUR = 12


@struct.dataclass
class BarkourCPGParams:
    frequency: float
    amp_0: float; amp_1: float; amp_2: float; amp_3: float
    amp_4: float; amp_5: float; amp_6: float; amp_7: float
    amp_8: float; amp_9: float; amp_10: float; amp_11: float
    phase_0: float; phase_1: float; phase_2: float; phase_3: float
    phase_4: float; phase_5: float; phase_6: float; phase_7: float
    phase_8: float; phase_9: float; phase_10: float; phase_11: float
    dt: float  # env physics dt (BarkourJoystick = 0.02 s)


def barkour_cpg_step(
    params: BarkourCPGParams, state: CPGState, obs: jnp.ndarray
) -> tuple[jnp.ndarray, CPGState]:
    """Open-loop sinusoidal CPG. ``obs`` is unused (pure pattern generator)."""
    t = state.time
    omega = 2.0 * jnp.pi * params.frequency
    amps = jnp.stack([
        params.amp_0, params.amp_1, params.amp_2, params.amp_3,
        params.amp_4, params.amp_5, params.amp_6, params.amp_7,
        params.amp_8, params.amp_9, params.amp_10, params.amp_11,
    ])
    phases = jnp.stack([
        params.phase_0, params.phase_1, params.phase_2, params.phase_3,
        params.phase_4, params.phase_5, params.phase_6, params.phase_7,
        params.phase_8, params.phase_9, params.phase_10, params.phase_11,
    ])
    action = amps * jnp.sin(omega * t + phases)
    action = jnp.clip(action, -1.0, 1.0)
    new_state = CPGState(time=t + params.dt)
    return action, new_state


_BARKOUR_CPG_LEARNABLE = (
    "frequency",
    "amp_0", "amp_1", "amp_2", "amp_3", "amp_4", "amp_5",
    "amp_6", "amp_7", "amp_8", "amp_9", "amp_10", "amp_11",
)
register_learnable_gains(barkour_cpg_step, _BARKOUR_CPG_LEARNABLE)


def _barkour_trot_anchor() -> tuple[float, list, list]:
    """Hand-tuned trot gait anchor (pre-DE). See header comment for layout.

    Diagonal pairs (FL+HR) vs (FR+HL) are antiphase. Within a leg, knee lifts
    slightly before hip swings forward (phase lead of pi/4).
    """
    freq = 2.0  # Hz
    # Amplitudes per actuator: abduction=0, hip=0.3, knee=0.4
    amp_abd, amp_hip, amp_knee = 0.0, 0.3, 0.4
    amps = [
        amp_abd, amp_hip, amp_knee,  # front-left
        amp_abd, amp_hip, amp_knee,  # hind-left  (antiphase with front-left)
        amp_abd, amp_hip, amp_knee,  # front-right (antiphase with front-left)
        amp_abd, amp_hip, amp_knee,  # hind-right (in phase with front-left)
    ]
    # Phases. Front-left/hind-right pair: phase 0. Hind-left/front-right: phi.
    pi = float(jnp.pi)
    knee_lead = pi / 4.0
    phases = [
        0.0,     0.0,     knee_lead,      # front-left  (pair A)
        0.0,     pi,      pi + knee_lead,  # hind-left   (pair B, antiphase)
        0.0,     pi,      pi + knee_lead,  # front-right (pair B)
        0.0,     0.0,     knee_lead,       # hind-right  (pair A)
    ]
    return freq, amps, phases


def make_barkour_cpg(dt: float = 0.02) -> tuple[BarkourCPGParams, CPGState]:
    """CPG for BarkourJoystick. Loads tuned params from cpg_tuned_barkourjoystick.json
    if present, else falls back to a hand-tuned trot gait."""
    tuned = _load_tuned("barkourjoystick")
    if tuned is not None:
        freq = float(tuned["frequency"])
        amps = [float(a) for a in tuned["amplitudes"]]
        phases = [float(p) for p in tuned["phases"]]
    else:
        freq, amps, phases = _barkour_trot_anchor()
    assert len(amps) == _N_BARKOUR and len(phases) == _N_BARKOUR
    params = BarkourCPGParams(
        frequency=freq,
        amp_0=amps[0], amp_1=amps[1], amp_2=amps[2], amp_3=amps[3],
        amp_4=amps[4], amp_5=amps[5], amp_6=amps[6], amp_7=amps[7],
        amp_8=amps[8], amp_9=amps[9], amp_10=amps[10], amp_11=amps[11],
        phase_0=phases[0], phase_1=phases[1], phase_2=phases[2], phase_3=phases[3],
        phase_4=phases[4], phase_5=phases[5], phase_6=phases[6], phase_7=phases[7],
        phase_8=phases[8], phase_9=phases[9], phase_10=phases[10], phase_11=phases[11],
        dt=float(dt),
    )
    return params, cpg_reset(params)


def make_barkour_cpg_expert() -> FunctionalExpertPolicy:
    """Return a FunctionalExpertPolicy-wrapped Barkour trot CPG."""
    params, zero_state = make_barkour_cpg()
    return FunctionalExpertPolicy(params, zero_state, barkour_cpg_step)
