#!/usr/bin/env python3
"""Generate ``docs/environments.md`` from the registry.

The environment table states shapes, baselines and tracked variables for
eighteen environments. Hand-maintained, it would be wrong within a release --
so it is derived from the registry instead, and ``tests/test_docs.py`` fails
if the checked-in file no longer matches what this produces.

    python scripts/generate_env_reference.py           # rewrite the file
    python scripts/generate_env_reference.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from target_gym.registry import GROUPS, REGISTRY  # noqa: E402

OUTPUT = ROOT / "docs" / "environments.md"
BLOB = "https://github.com/YannBerthelot/TargetGym/blob/main"

# Spelled out rather than left as a digit, because the count sits in running
# prose -- and computed rather than typed, because a hand-written "eighteen"
# went stale the moment the nineteenth environment was registered, in a file
# whose entire purpose is not to go stale.
_WORDS = {
    12: "Twelve",
    16: "Sixteen",
    18: "Eighteen",
    19: "Nineteen",
    20: "Twenty",
    21: "Twenty-one",
    22: "Twenty-two",
    23: "Twenty-three",
    24: "Twenty-four",
    25: "Twenty-five",
    26: "Twenty-six",
}


def _count(n: int) -> str:
    return _WORDS.get(n, str(n))


HEADER = f"""# Environment reference

{_count(len(REGISTRY))} environments, every one a *target MDP*: the objective is
to reach and hold a subset of the state space against disturbances, not to reach
a goal and stop.

<!-- Generated by scripts/generate_env_reference.py. Do not edit by hand:
     tests/test_docs.py fails when this file and the registry disagree. -->

Every environment implements the same interface, so the table below is the
whole of what differs between them:

- **Observation / Action** are the array shapes.
- **Tracked** is the quantity the target applies to, exposed at
  `env.obs_value_index` with its setpoint at `env.obs_target_index`, and named
  by `env.tracked_names`.
- **PID / MPC** say whether a baseline ships. Where one does not, the registry
  records why in `baselines_note` rather than leaving it silent, and the same
  note qualifies a shipped one that needs it (`patrol_bearing_only`'s MPC is a
  full-state bound).
- **Physics** links the environment's contract: sourced parameters, published
  validation targets asserted by tests, and quantified known deviations.

Load any of them by registry name:

```python
from target_gym.registry import REGISTRY

spec = REGISTRY["boiler_drum"]
env, params = spec.make_env(), spec.params_cls()
```
"""


def _physics_link(env) -> str:
    module = type(env).__module__
    for suffix in (".env_jax", ".marl"):
        module = module.removesuffix(suffix)
    path = pathlib.Path("src") / module.replace(".", "/") / "PHYSICS.md"
    if not (ROOT / path).exists():
        return "--"
    # Absolute, not relative: each PHYSICS.md lives beside the code it
    # documents, under src/, which is outside the mkdocs source tree. A
    # relative "../src/..." link resolves on GitHub but 404s on the built
    # site, and mkdocs --strict refuses to build at all.
    return f"[contract]({BLOB}/{path.as_posix()})"


def build() -> str:
    lines = [HEADER]
    for group_key, group_name in GROUPS.items():
        specs = [s for s in REGISTRY.values() if s.group == group_key]
        if not specs:
            continue
        lines.append(f"\n## {group_name}\n")
        # The group's mosaic, where one has been built. This is the page the
        # full gallery lives on -- the homepage carries only the curated four,
        # so that a reader meets four large tiles rather than twenty-two small
        # ones. Emitted here rather than hand-written so a new environment
        # cannot appear in the table while the picture above it still shows the
        # old set.
        mosaic = ROOT / "videos" / f"mosaic_{group_key}.webp"
        if mosaic.exists():
            lines.append(
                f'<p align="center">'
                f'<img src="../videos/mosaic_{group_key}.webp" width="100%"/>'
                f"</p>\n"
            )
        lines.append(
            "| Environment | Cite as | Observation | Action | Tracked | PID | MPC "
            "| Physics |"
        )
        lines.append("|---|---|---|---|---|---|---|---|")
        for spec in specs:
            env = spec.make_env()
            params = spec.params_cls()
            obs = env.observation_space(params).shape
            act = env.action_space(params).shape
            tracked = ", ".join(getattr(env, "tracked_names", ()) or ["--"])
            lines.append(
                f"| `{spec.name}` | `{spec.versioned_name}` | {tuple(obs)} | "
                f"{tuple(act)} | {tracked} | "
                f"{'yes' if spec.has_pid else 'no'} | "
                f"{'yes' if spec.has_mpc else 'no'} | {_physics_link(env)} |"
            )
        notes = [s for s in specs if s.baselines_note]
        for spec in notes:
            lines.append(f"\n> `{spec.name}` -- {spec.baselines_note}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check", action="store_true", help="exit 1 if the checked-in file is stale"
    )
    args = ap.parse_args()

    content = build()
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT} is out of date; run scripts/generate_env_reference.py")
            return 1
        print(f"{OUTPUT} is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
